INSERT INTO plants (common_name, scientific_name, height, cycle, hardiness, watering, sunlight, flowers, edible, img)
VALUES
(
'European Silver Fir',
'Abies alba',
60
'Perennial',
7,
'Frequent',
'Full Sun',
0,
0,
'https://perenual.com/storage/species_image/1_abies_alba/regular/1536px-Abies_alba_SkalitC3A9.jpg'
),
(
'Pyramidalis Silver Fir',
'Abies alba Pyramidalis'
30,
'Perennial',
4
'Average',
'Full Sun',
0,
0,
'https://perenual.com/storage/species_image/2_abies_alba_pyramidalis/regular/49255769768_df55596553_b.jpg'
),
(
“White Fir”,
“Abies concolor”,
45,
'Perennial',
3,
'Average',
'Part Shade',
1,
0,
'https://perenual.com/storage/species_image/3_abies_concolor/regular/52292935430_f4f3b22614_b.jpg',
),
(
'Candicans White Fir',
'Abies concolor Candicans',
30,
'Perennial',
4,
'Average',
'Full Sun',
0
0,
'https://perenual.com/storage/species_image/4_abies_concolor_candicans/regular/49283844888_332c9e46f2_b.jpg'
),
(
'Fraser Fir',
'Abies fraseri',
35,
'Perennial',
6,
'Frequent',
'Part Shade',
1,
0,
'https://perenual.com/storage/species_image/5_abies_fraseri/regular/36843539702_e80fc436e0_b.jpg'
),
(
'Yarrow',
'Achillea millefolium little moonshine'
3,
'Perennial',
6,
'Average',
'Full Sun',
1,
0,
'https://perenual.com/storage/species_image/480_achillea_millefolium_little_moonshine/regular/yarrow-water-wise-plant-summer-plant-plant.jpg'
),
(
'Woolly Yarrow',
'Achillea tomentosa Aurea'
1,
'Perennial',
5,
'Average',
'Full Sun',
1,
0,
'https://perenual.com/storage/species_image/500_achillea_tomentosa_aurea/regular/2560px-Achillea_tomentosa1.jpg'
),
(
'Golden Spaniard',
'Aciphylla aurea',
3,
'Perennial',
8,
'Average',
'Full Sun',
1,
1,
'https://perenual.com/storage/species_image/503_aciphylla_aurea/regular/2560px-Aciphylla_aurea_kz13.jpg'
),
(
'paurotis palm',
'Acoelorrhaphe wrightii',
20,
'Perennial',
11,
'Frequent',
'Full Sun',
0,
0,
'https://perenual.com/storage/species_image/504_acoelorrhaphe_wrightii/regular/24857511382_4d8a1ef1dc_b.jpg'
),
(
'Monkshood',
'Aconitum bulbuliferum Monk Gone Wild',
10,
'Perennial',
7,
'Average',
'Full Sun',
1,
0,
'https://perenual.com/storage/species_image/505_aconitum_bulbuliferum_monk_gone_wild/regular/50275942563_55509f4393_b.jpg'
),
(
'Azure Monkshood',
'Aconitum carmichaelii Arendsii',
4,
'Perennial',
5,
'Average',
'Full Sun',
1,
0,
'https://perenual.com/storage/species_image/506_aconitum_carmichaelii_arendsii/regular/51585221643_efcbab382f_b.jpg'
),
(
'Climbing Monks Hood',
'Aconitum hemsleyanum',
10,
'Perennial',
6,
'Average',
'Part Shade',
1,
0,
'https://perenual.com/storage/species_image/509_aconitum_hemsleyanum/regular/6166179411_f2598d51ec_b.jpg'
),
(
'Grassy-leaved Sweet Flag',
'Acorus gramineus',
1,
'Perennial',
8,
'Frequent',
'Part Shade',
0,
0,
'https://perenual.com/storage/species_image/515_acorus_gramineus/regular/43357997720_ae5f9d1fe6_b.jpg'
),
(
'Bugbane',
'Actaea simplex',
4,
'Perennial',
6,
'Average',
'Part Shade',
1,
0,
'https://perenual.com/storage/species_image/528_actaea_simplex/regular/51618506667_d2af922035_b.jpg'
),
(
'Kiwifruit',
'Actinidia deliciosa',
30,
'Perennial',
9,
'Average',
'Full Sun',
1,
1,
'https://perenual.com/storage/species_image/536_actinidia_deliciosa/regular/25119432356_f10218d971_b.jpg'
),
(
'Variegated Kiwi Vine',
'Actinidia kolomikta',
20,
'Perennial',
6,
'Average',
'Part Shade',
1,
1,
'https://perenual.com/storage/species_image/537_actinidia_kolomikta/regular/51490517809_fc47df43b2_b.jpg'
),
(
'Desert Rose',
'Adenium obesum',
9,
'Perennial',
12,
'Minimum',
'Full Sun',
1,
0,
'https://perenual.com/storage/species_image/540_adenium_obesum/regular/9244335137_6d662ed77c_b.jpg'
),
(
'Ladybells',
'Adenophora Amethyst',
3,
'Perennial',
6,
'Average',
'Part Shade',
1,
0,
'https://perenual.com/storage/species_image/541_adenophora_amethyst/regular/2448px-Adenophora_cf._aurita_282098345350529.jpg'
),
(
'maidenhair fern',
'Adiantum capillus-veneris',
2,
'Perennial',
7,
'Average',
'Part Shade',
0,
0,
'https://perenual.com/storage/species_image/543_adiantum_capillus-veneris/regular/49636882698_cb4fa4c685_b.jpg'
),
(
'Chinese buttonbush',
'Adina rubella',
10,
'Perennial',
8,
'Average',
'Part Shade',
1,
0,
'https://perenual.com/storage/species_image/547_adina_rubella/regular/51851513968_f8b102672f_b.jpg'
),
(
'Bishops Weed',
'Aegopodium podagraria Variegatum',
1,
'Perennial',
6,
'Frequent',
'Full Sun',
0,
0,
'https://perenual.com/storage/species_image/550_aegopodium_podagraria_variegatum/og/34713982780_3954944e69_b.jpg'
),
(
'Red Horse Chestnut',
'Aesculus carnea',
40,
'Perennial',
7,
'Average',
'Full Sun',
1,
0,
'https://perenual.com/storage/species_image/554_aesculus_carnea/regular/52059409034_87b7e2ed86_b.jpg'
),
(
'Bottlebrush Buckeye',
'Aesculus parviflora var. serotina',
20,
'Perennial',
6,
'Average',
'Full Shade',
1,
0,
'https://perenual.com/storage/species_image/565_aesculus_parviflora_var_serotina/regular/28238288795_e001a089c1_b.jpg'
),
(
'Slenderleaf 0 Foxglove',
'Agalinis tenuifolia',
1.5,
'Annual',
6,
'Average',
'Full Sun',
1,
0,
'https://perenual.com/storage/species_image/571_agalinis_tenuifolia/regular/51729887719_21b2944da8_b.jpg'
),
(
'Lily of the Nile',
'Agapanthus group',
4,
'Perennial',
8,
'Average',
'Part Shade',
1,
0,
'https://perenual.com/storage/species_image/575_agapanthus_group/regular/2742717111_04f3b1bee3_b.jpg'
),
(
'Giant Hyssop',
'Agastache Ava',
4,
'Perennial',
7,
'Average',
'Full Sun',
1,
0,
'https://perenual.com/storage/species_image/581_agastache_ava/regular/lemonade-plant-violet-close-up-bokeh-purple-flower.jpg'
),
(
'Anise Hyssop',
'Agastache foeniculum',
4,
'Perennial',
6,
'Average',
'Part Shade',
1,
1,
'https://perenual.com/storage/species_image/589_agastache_foeniculum/regular/9497142760_cc4468f21d_b.jpg'
),
(
'Yellow Giant Hyssop',
'Agastache nepetoides',
6,
'Perennial',
5,
'Average',
'Part Shade',
1,
0,
'https://perenual.com/storage/species_image/589_agastache_foeniculum/regular/9497142760_cc4468f21d_b.jpg'
),
(
'American Century Plant',
'Agave americana',
6,
'Perennial',
9,
'Minimum',
'Full Sun',
0,
0,
'https://perenual.com/storage/species_image/606_agave_americana/regular/51350574500_deff0b0166_b.jpg'
),
(
'Spineless Jade Agave',
'Agave desmetiana',
3,
'Perennial',
9,
'Average',
'Part Shade',
0,
0,
'https://perenual.com/storage/species_image/609_agave_desmetiana/regular/32890107377_b45716fb43_b.jpg'
),
(
'White Snakeroot',
'Ageratina altissima',
5,
'Perennial',
6,
'Average',
'Part Shade',
1,
0,
'https://perenual.com/storage/species_image/619_ageratina_altissima/regular/21285911241_2a4f83a3d4_b.jpg'
),
(
'Floss Flower',
'Ageratum houstonianum Blue Horizon',
3,
'Annual',
6,
'Average',
'Part Shade',
1,
0,
'https://perenual.com/storage/species_image/622_ageratum_houstonianum_blue_horizon/regular/Ageratum_houstonianum_cv.jpg'
),
(
'Creeping Bent Grass',
'Agrostis palustris',
0.5,
'Perennial',
5,
'Average',
'Part Shade',
0,
0,
'https://perenual.com/storage/species_image/629_agrostis_palustris_no_mow/regular/Agrostis_Wuchs.jpg'
),
(
'Bugleweed',
'Ajuga reptans Binblasca',
0.75,
'Perennial',
6,
'Average',
'Part Shade',
1,
0,
'https://perenual.com/storage/species_image/637_ajuga_reptans_binblasca_black_scallop/regular/52105985298_bef92726b8_b.jpg'
),
(
'Leek',
'Allium ampeloprasum',
2.5,
'Perennial',
5,
'Average',
'Part Shade',
1,
1,
'https://perenual.com/storage/species_image/665_allium_ampeloprasum/regular/49970438148_ca26f3b176_b.jpg'
),
(
'Onion',
'Allium cepa',
1.5,
'Perennial',
8,
'Average',
'Full Sun',
0,
1,
'https://perenual.com/storage/species_image/667_allium_cepa/regular/24466615444_a161c175d3_b.jpg'
),
(
'Chives',
'Allium Chivette',
1.5,
'Perennial',
6,
'Average',
'Full Sun',
1,
1,
'https://perenual.com/storage/species_image/669_allium_chivette/regular/pexels-photo-8332487.jpg'
),
(
'Garlic Chives',
'Allium tuberosum',
1.5,
'Perennial',
6,
'Average',
'Full Sun',
1,
1,
'https://perenual.com/storage/species_image/697_allium_tuberosum/regular/51949630538_39d542591d_b.jpg'
),
(
'Elephant's Ear',
'Alocasia low rider',
2,
'Perennial',
9,
'Average',
'Part Shade',
0,
0,
'https://perenual.com/storage/species_image/714_alocasia_low_rider/regular/8415446715_799e70b503_b.jpg'
),
(
'Torch Plant',
'Aloe aristata',
0.75,
'Perennial',
9,
'Average',
'Part Shade',
1,
0,
'https://perenual.com/storage/species_image/719_aloe_aristata/regular/23962599232_fdc4070814_b.jpg'
),
(
'Karoo Aloe',
'Aloe longistyla',
0.75,
'Perennial',
10,
'Average',
'Part Shade',
1,
0,
'https://perenual.com/storage/species_image/722_aloe_longistyla/regular/pexels-photo-6156450.jpg'
),
(
'Yemen tree aloe',
'Aloe sabaea',
10,
'Perennial',
9,
'Minimum',
'Full Sun',
1,
0,
'https://perenual.com/storage/species_image/725_aloe_sabaea/regular/488c2e98bae5c75ae8edcb2901f56875341dae17.jpg'
),
(
'Eared Lady Fern',
'Athyrium otophorum',
2,
'Perennial',
7,
'Average',
'Full Shade',
0,
0,
'https://perenual.com/storage/species_image/725_aloe_sabaea/regular/488c2e98bae5c75ae8edcb2901f56875341dae17.jpg'
),
(
'Mountain Spinach',
'Atriplex hortensis',
6,
'Perennial',
6,
'Average',
'Part Shade',
0,
1,
'https://perenual.com/storage/species_image/1144_atriplex_hortensis/og/29489868944_06b587da94_b.jpg'
),
(
'Spotted Laurel',
'Aucuba japonica',
10,
'Perennial',
8,
'Average',
'Full Shade',
1,
0,
'https://perenual.com/storage/species_image/1146_aucuba_japonica/regular/Aucuba_japonica_cv._27Crotonifolia27.jpg'
),
(
'Basket of Gold',
'Aurinia saxatilis Dudley Nevill Variegated',
1,
'Perennial',
6,
'Minimum',
'Part Shade',
1,
0,
'https://perenual.com/storage/species_image/1152_aurinia_saxatilis_dudley_nevill_variegated/regular/52522771711_19610b5349_b.jpg'
),
(
'Water Fern',
'Azolla filiculoides',
0.25,
'Perennial',
9,
'Frequent',
'Part Shade',
0,
0,
'https://perenual.com/storage/species_image/1159_azolla_filiculoides/regular/2560px-Azolla_filiculoides_01.jpg'
),
(
'Dwarf Chapparal-broom',
'Baccharis pilularis Pigeon Point',
2,
'Perennial',
9,
'Average',
'Part Shade',
0,
0,
'https://perenual.com/storage/species_image/1163_baccharis_pilularis_pigeon_point/regular/10355511633_50f94d204d_b.jpg'
),
(
'White False Indigo',
'Baptisia alba var. macrophylla',
4,
'Perennial',
7,
'Minimum',
'Part Shade',
1,
0,
'https://perenual.com/storage/species_image/1167_baptisia_alba_var_macrophylla/regular/Baptisia_lactea.jpg'
);
