INSERT INTO plants (common_name, scientific_name, height, cycle, hardiness, watering, sunlight, flowers, edible, img)
VALUES
(
'European Silver Fir',
'Abies alba',
60,
'Perennial',
7,
'Frequent',
'Full Sun',
false,
false,
'https://perenual.com/storage/species_image/1_abies_alba/regular/1536px-Abies_alba_SkalitC3A9.jpg'
),
(
'Pyramidalis Silver Fir',
'Abies alba Pyramidalis',
30,
'Perennial',
4,
'Average',
'Full Sun',
false,
false,
'https://perenual.com/storage/species_image/2_abies_alba_pyramidalis/regular/49255769768_df55596553_b.jpg'
),
(
'White Fir',
'Abies concolor',
45,
'Perennial',
3,
'Average',
'Part Shade',
true,
false,
'https://perenual.com/storage/species_image/3_abies_concolor/regular/52292935430_f4f3b22614_b.jpg'
),
(
'Candicans White Fir',
'Abies concolor Candicans',
30,
'Perennial',
4,
'Average',
'Full Sun',
false,
false,
'https://perenual.com/storage/species_image/4_abies_concolor_candicans/regular/49283844888_332c9e46f2_b.jpg'
),
(
'Fraser Fir',
'Abies fraseri',
35,
'Perennial',
6,
'Frequent',
'Part Shade',
true,
false,
'https://perenual.com/storage/species_image/5_abies_fraseri/regular/36843539702_e80fc436e0_b.jpg'
),
(
'Yarrow',
'Achillea millefolium little moonshine',
3,
'Perennial',
6,
'Average',
'Full Sun',
true,
false,
'https://perenual.com/storage/species_image/480_achillea_millefolium_little_moonshine/regular/yarrow-water-wise-plant-summer-plant-plant.jpg'
),
(
'Woolly Yarrow',
'Achillea tomentosa Aurea',
1,
'Perennial',
5,
'Average',
'Full Sun',
true,
false,
'https://perenual.com/storage/species_image/500_achillea_tomentosa_aurea/regular/2560px-Achillea_tomentosa1.jpg'
),
(
'Golden Spaniard',
'Aciphylla aurea',
3,
'Perennial',
8,
'Average',
'Full Sun',
true,
true,
'https://perenual.com/storage/species_image/503_aciphylla_aurea/regular/2560px-Aciphylla_aurea_kz13.jpg'
),
(
'paurotis palm',
'Acoelorrhaphe wrightii',
20,
'Perennial',
11,
'Frequent',
'Full Sun',
false,
false,
'https://perenual.com/storage/species_image/504_acoelorrhaphe_wrightii/regular/24857511382_4d8a1ef1dc_b.jpg'
),
(
'Monkshood',
'Aconitum bulbuliferum Monk Gone Wild',
10,
'Perennial',
7,
'Average',
'Full Sun',
true,
false,
'https://perenual.com/storage/species_image/505_aconitum_bulbuliferum_monk_gone_wild/regular/50275942563_55509f4393_b.jpg'
),
(
'Azure Monkshood',
'Aconitum carmichaelii Arendsii',
4,
'Perennial',
5,
'Average',
'Full Sun',
true,
false,
'https://perenual.com/storage/species_image/506_aconitum_carmichaelii_arendsii/regular/51585221643_efcbab382f_b.jpg'
),
(
'Climbing Monks Hood',
'Aconitum hemsleyanum',
10,
'Perennial',
6,
'Average',
'Part Shade',
true,
false,
'https://perenual.com/storage/species_image/509_aconitum_hemsleyanum/regular/6166179411_f2598d51ec_b.jpg'
),
(
'Grassy-leaved Sweet Flag',
'Acorus gramineus',
1,
'Perennial',
8,
'Frequent',
'Part Shade',
false,
false,
'https://perenual.com/storage/species_image/515_acorus_gramineus/regular/43357997720_ae5f9d1fe6_b.jpg'
),
(
'Bugbane',
'Actaea simplex',
4,
'Perennial',
6,
'Average',
'Part Shade',
true,
false,
'https://perenual.com/storage/species_image/528_actaea_simplex/regular/51618506667_d2af922035_b.jpg'
),
(
'Kiwifruit',
'Actinidia deliciosa',
30,
'Perennial',
9,
'Average',
'Full Sun',
true,
true,
'https://perenual.com/storage/species_image/536_actinidia_deliciosa/regular/25119432356_f10218d971_b.jpg'
),
(
'Variegated Kiwi Vine',
'Actinidia kolomikta',
20,
'Perennial',
6,
'Average',
'Part Shade',
true,
true,
'https://perenual.com/storage/species_image/537_actinidia_kolomikta/regular/51490517809_fc47df43b2_b.jpg'
),
(
'Desert Rose',
'Adenium obesum',
9,
'Perennial',
12,
'Minimum',
'Full Sun',
true,
false,
'https://perenual.com/storage/species_image/540_adenium_obesum/regular/9244335137_6d662ed77c_b.jpg'
),
(
'Ladybells',
'Adenophora Amethyst',
3,
'Perennial',
6,
'Average',
'Part Shade',
true,
false,
'https://perenual.com/storage/species_image/541_adenophora_amethyst/regular/2448px-Adenophora_cf._aurita_282098345350529.jpg'
),
(
'maidenhair fern',
'Adiantum capillus-veneris',
2,
'Perennial',
7,
'Average',
'Part Shade',
false,
false,
'https://perenual.com/storage/species_image/543_adiantum_capillus-veneris/regular/49636882698_cb4fa4c685_b.jpg'
),
(
'Chinese buttonbush',
'Adina rubella',
10,
'Perennial',
8,
'Average',
'Part Shade',
true,
false,
'https://perenual.com/storage/species_image/547_adina_rubella/regular/51851513968_f8b102672f_b.jpg'
),
(
'Bishops Weed',
'Aegopodium podagraria Variegatum',
1,
'Perennial',
6,
'Frequent',
'Full Sun',
false,
false,
'https://perenual.com/storage/species_image/550_aegopodium_podagraria_variegatum/og/34713982780_3954944e69_b.jpg'
),
(
'Red Horse Chestnut',
'Aesculus carnea',
40,
'Perennial',
7,
'Average',
'Full Sun',
true,
false,
'https://perenual.com/storage/species_image/554_aesculus_carnea/regular/52059409034_87b7e2ed86_b.jpg'
),
(
'Bottlebrush Buckeye',
'Aesculus parviflora var. serotina',
20,
'Perennial',
6,
'Average',
'Full Shade',
true,
false,
'https://perenual.com/storage/species_image/565_aesculus_parviflora_var_serotina/regular/28238288795_e001a089c1_b.jpg'
),
(
'Slenderleaf False Foxglove',
'Agalinis tenuifolia',
1.5,
'Annual',
6,
'Average',
'Full Sun',
true,
false,
'https://perenual.com/storage/species_image/571_agalinis_tenuifolia/regular/51729887719_21b2944da8_b.jpg'
),
(
'Lily of the Nile',
'Agapanthus group',
4,
'Perennial',
8,
'Average',
'Part Shade',
true,
false,
'https://perenual.com/storage/species_image/575_agapanthus_group/regular/2742717111_04f3b1bee3_b.jpg'
),
(
'Giant Hyssop',
'Agastache Ava',
4,
'Perennial',
7,
'Average',
'Full Sun',
true,
false,
'https://perenual.com/storage/species_image/581_agastache_ava/regular/lemonade-plant-violet-close-up-bokeh-purple-flower.jpg'
),
(
'Anise Hyssop',
'Agastache foeniculum',
4,
'Perennial',
6,
'Average',
'Part Shade',
true,
true,
'https://perenual.com/storage/species_image/589_agastache_foeniculum/regular/9497142760_cc4468f21d_b.jpg'
),
(
'Yellow Giant Hyssop',
'Agastache nepetoides',
6,
'Perennial',
5,
'Average',
'Part Shade',
true,
false,
'https://perenual.com/storage/species_image/589_agastache_foeniculum/regular/9497142760_cc4468f21d_b.jpg'
),
(
'American Century Plant',
'Agave americana',
6,
'Perennial',
9,
'Minimum',
'Full Sun',
false,
false,
'https://perenual.com/storage/species_image/606_agave_americana/regular/51350574500_deff0b0166_b.jpg'
),
(
'Spineless Jade Agave',
'Agave desmetiana',
3,
'Perennial',
9,
'Average',
'Part Shade',
false,
false,
'https://perenual.com/storage/species_image/609_agave_desmetiana/regular/32890107377_b45716fb43_b.jpg'
),
(
'White Snakeroot',
'Ageratina altissima',
5,
'Perennial',
6,
'Average',
'Part Shade',
true,
false,
'https://perenual.com/storage/species_image/619_ageratina_altissima/regular/21285911241_2a4f83a3d4_b.jpg'
),
(
'Floss Flower',
'Ageratum houstonianum Blue Horizon',
3,
'Annual',
6,
'Average',
'Part Shade',
true,
false,
'https://perenual.com/storage/species_image/622_ageratum_houstonianum_blue_horizon/regular/Ageratum_houstonianum_cv.jpg'
),
(
'Creeping Bent Grass',
'Agrostis palustris',
0.5,
'Perennial',
5,
'Average',
'Part Shade',
false,
false,
'https://perenual.com/storage/species_image/629_agrostis_palustris_no_mow/regular/Agrostis_Wuchs.jpg'
),
(
'Bugleweed',
'Ajuga reptans Binblasca',
0.75,
'Perennial',
6,
'Average',
'Part Shade',
true,
false,
'https://perenual.com/storage/species_image/637_ajuga_reptans_binblasca_black_scallop/regular/52105985298_bef92726b8_b.jpg'
),
(
'Leek',
'Allium ampeloprasum',
2.5,
'Perennial',
5,
'Average',
'Part Shade',
true,
true,
'https://perenual.com/storage/species_image/665_allium_ampeloprasum/regular/49970438148_ca26f3b176_b.jpg'
),
(
'Onion',
'Allium cepa',
1.5,
'Perennial',
8,
'Average',
'Full Sun',
false,
true,
'https://perenual.com/storage/species_image/667_allium_cepa/regular/24466615444_a161c175d3_b.jpg'
),
(
'Chives',
'Allium Chivette',
1.5,
'Perennial',
6,
'Average',
'Full Sun',
true,
true,
'https://perenual.com/storage/species_image/669_allium_chivette/regular/pexels-photo-8332487.jpg'
),
(
'Garlic Chives',
'Allium tuberosum',
1.5,
'Perennial',
6,
'Average',
'Full Sun',
true,
true,
'https://perenual.com/storage/species_image/697_allium_tuberosum/regular/51949630538_39d542591d_b.jpg'
),
(
'Elephant''s Ear',
'Alocasia low rider',
2,
'Perennial',
9,
'Average',
'Part Shade',
false,
false,
'https://perenual.com/storage/species_image/714_alocasia_low_rider/regular/8415446715_799e70b503_b.jpg'
),
(
'Torch Plant',
'Aloe aristata',
0.75,
'Perennial',
9,
'Average',
'Part Shade',
true,
false,
'https://perenual.com/storage/species_image/719_aloe_aristata/regular/23962599232_fdc4070814_b.jpg'
),
(
'Karoo Aloe',
'Aloe longistyla',
0.75,
'Perennial',
10,
'Average',
'Part Shade',
true,
false,
'https://perenual.com/storage/species_image/722_aloe_longistyla/regular/pexels-photo-6156450.jpg'
),
(
'Yemen tree aloe',
'Aloe sabaea',
10,
'Perennial',
9,
'Minimum',
'Full Sun',
true,
false,
'https://perenual.com/storage/species_image/725_aloe_sabaea/regular/488c2e98bae5c75ae8edcb2901f56875341dae17.jpg'
),
(
'Eared Lady Fern',
'Athyrium otophorum',
2,
'Perennial',
7,
'Average',
'Full Shade',
false,
false,
'https://perenual.com/storage/species_image/725_aloe_sabaea/regular/488c2e98bae5c75ae8edcb2901f56875341dae17.jpg'
),
-- removed plant for now, image size is taller than the others and it's screwing up the formatting
-- (
-- 'Mountain Spinach',
-- 'Atriplex hortensis',
-- 6,
-- 'Perennial',
-- 6,
-- 'Average',
-- 'Part Shade',
-- false,
-- true,
-- 'https://perenual.com/storage/species_image/1144_atriplex_hortensis/og/29489868944_06b587da94_b.jpg'
-- ),
(
'Spotted Laurel',
'Aucuba japonica',
10,
'Perennial',
8,
'Average',
'Full Shade',
true,
false,
'https://perenual.com/storage/species_image/1146_aucuba_japonica/regular/Aucuba_japonica_cv._27Crotonifolia27.jpg'
),
(
'Basket of Gold',
'Aurinia saxatilis Dudley Nevill Variegated',
1,
'Perennial',
6,
'Minimum',
'Part Shade',
true,
false,
'https://perenual.com/storage/species_image/1152_aurinia_saxatilis_dudley_nevill_variegated/regular/52522771711_19610b5349_b.jpg'
),
(
'Water Fern',
'Azolla filiculoides',
0.25,
'Perennial',
9,
'Frequent',
'Part Shade',
false,
false,
'https://perenual.com/storage/species_image/1159_azolla_filiculoides/regular/2560px-Azolla_filiculoides_01.jpg'
),
(
'Dwarf Chapparal-broom',
'Baccharis pilularis Pigeon Point',
2,
'Perennial',
9,
'Average',
'Part Shade',
false,
false,
'https://perenual.com/storage/species_image/1163_baccharis_pilularis_pigeon_point/regular/10355511633_50f94d204d_b.jpg'
),
(
'White False Indigo',
'Baptisia alba var. macrophylla',
4,
'Perennial',
7,
'Minimum',
'Part Shade',
true,
false,
'https://perenual.com/storage/species_image/1167_baptisia_alba_var_macrophylla/regular/Baptisia_lactea.jpg'
),
(
'Ceylon spinach',
'Basella rubra Red Stem',
6,
'Perennial',
9,
'Average',
'Full Sun',
true,
true,
'https://perenual.com/storage/species_image/1189_basella_rubra_red_stem/regular/24603734219_d4ea98b0cc_b.jpg'
),
(
'Beesia',
'Beesia deltophylla',
1.5,
'Perennial',
8,
'Average',
'Full Shade',
true,
false,
'https://perenual.com/storage/species_image/1193_beesia_deltophylla/regular/7246439522_8b7c73cb31_b.jpg'
),
(
'Begonia',
'Begonia Bepared DRAGON WING RED',
1.5,
'Perennial',
11,
'Average',
'Part Shade',
true,
false,
'https://perenual.com/storage/species_image/1196_begonia_bepared_dragon_wing_red/regular/52542250837_647bf91a34_b.jpg'
),
(
'Hybrid Tuberous Begonia',
'Begonia tuberhybrida Jurassic Silver Swirl',
1.75,
'Perennial',
11,
'Average',
'Part Shade',
true,
false,
'https://perenual.com/storage/species_image/1224_begonia_tuberhybrida_jurassic_silver_swirl/regular/28152488224_06e2aca626_b.jpg'
),
(
'English daisy',
'Bellis perennis BELLISSIMA RED',
0.5,
'Perennial',
6,
'Average',
'Part Shade',
true,
false,
'https://perenual.com/storage/species_image/1228_bellis_perennis_bellissima_red/regular/daisies-red-flowers-spring-garden-nature.jpg'
),
(
'Barberry',
'Berberis Cally Rose',
5,
'Perennial',
9,
'Average',
'Part Shade',
true,
true,
'https://perenual.com/storage/species_image/1234_berberis_cally_rose/regular/28742921498_35f288d6e2_b.jpg'
),
(
'Jepson''s Oregon-grape',
'Berberis dictyota',
6,
'Perennial',
9,
'Minimum',
'Part Shade',
true,
false,
'https://perenual.com/storage/species_image/1235_berberis_dictyota/regular/25798467545_4609c916be_b.jpg'
),
(
'Japanese Barberry',
'Berberis thunbergii Aurea',
4,
'Perennial',
6,
'Minimum',
'Full Sun',
true,
false,
'https://perenual.com/storage/species_image/1242_berberis_thunbergii_aurea/regular/4532852304_81263a1268_b.jpg'
),
(
'Pigsqueak',
'Bergenia cordifolia',
1.5,
'Perennial',
6,
'Average',
'Full Shade',
true,
false,
'https://perenual.com/storage/species_image/1259_bergenia_cordifolia/regular/15401481825_f296996885_b.jpg'
),
-- IMAGE LINK DEFUNCT
-- (
-- 'Bergenia',
-- 'Bergenia Silberlicht SILVERLIGHT',
-- 1.5,
-- 'Perennial',
-- 6,
-- 'Average',
-- 'Full Shade',
-- true,
-- false,
-- 'https://perenual.com/storage/species_image/1268_bergenia_silberlicht_silverlight/regular/bergenia-flower-shrub-flowers.jpg'
-- ),
(
'Green Eyes',
'Berlandiera texana',
3,
'Perennial',
7,
'Minimum',
'Full Sun',
true,
false,
'https://perenual.com/storage/species_image/1271_berlandiera_texana/regular/4c60390f41944819b23434133d60526423013ea3.jpg'
),
(
'Beet',
'Beta vulgaris Bull''s Blood',
1.5,
'Annual',
6,
'Average',
'Full Sun',
false,
true,
'https://perenual.com/storage/species_image/1274_beta_vulgaris_garden_beet_group_bulls_blood/regular/2560px-Beta_vulgaris2C_San_Francisco_farmers_market.jpg'
),
(
'Swiss chard',
'Beta vulgaris Northern Lights',
2,
'Annual',
6,
'Average',
'Full Sun',
false,
true,
'https://perenual.com/storage/species_image/1277_beta_vulgaris_leaf_beet_group_northern_lights/og/51497846878_e9e9289222_b.jpg'
),
(
'Chinese ground orchid',
'Bletilla striata',
1.5,
'Perennial',
7,
'Average',
'Part Shade',
true,
false,
'https://perenual.com/storage/species_image/1299_bletilla_striata/regular/46779845065_57a4c9f61d_b.jpg'
),
(
'False Aster',
'Boltonia asteroides var. latisquama Snowbank',
6,
'Perennial',
7,
'Average',
'Part Shade',
true,
false,
'https://perenual.com/storage/species_image/1306_boltonia_asteroides_var_latisquama_snowbank/regular/52583401176_4dab1f4031_b.jpg'
),
(
'Sideoats Grass',
'Bouteloua curtipendula',
2.5,
'Perennial',
7,
'Minimum',
'Part Shade',
true,
false,
'https://perenual.com/storage/species_image/1309_bouteloua_curtipendula/regular/20481812753_c93285f109_b.jpg'
),
(
'Blue grama',
'Bouteloua gracilis Blonde Ambition',
2.5,
'Perennial',
7,
'Minimum',
'Full Sun',
true,
false,
'https://perenual.com/storage/species_image/1311_bouteloua_gracilis_blonde_ambition/regular/Bouteloua_gracilis_27Blonde_Ambition27_kz1.jpg'
),
(
'Rapeseed',
'Brassica napus (Oleifera Group)',
2,
'Annual',
7,
'Average',
'Full Sun',
false,
true,
'https://perenual.com/storage/species_image/1318_brassica_napus_oleifera_group/regular/52176476596_b973b8482f_b.jpg'
),
(
'Cabbage',
'Brassica oleracea (Capitata Group)',
1.5,
'Annual',
7,
'Average',
'Full Sun',
false,
true,
'https://perenual.com/storage/species_image/1322_brassica_oleracea_capitata_group/regular/2671495796_c0bdc6bd99_b.jpg'
),
(
'Broccoli',
'Brassica oleracea (Italica Group)',
1.5,
'Annual',
7,
'Average',
'Full Sun',
false,
true,
'https://perenual.com/storage/species_image/1327_brassica_oleracea_italica_group/og/1558498515_51e566c692_b.jpg'
),
(
'Turnip',
'Brassica rapa (Rapifera Group)',
1.5,
'Annual',
7,
'Average',
'Full Sun',
false,
true,
'https://perenual.com/storage/species_image/1333_brassica_rapa_rapifera_group/regular/51816290342_771a199fd5_b.jpg'
),
(
'Pak-choi',
'Brassica rapa (Chinensis Group)',
1.5,
'Annual',
7,
'Average',
'Part Shade',
false,
true,
'https://perenual.com/storage/species_image/1330_brassica_rapa_chinensis_group/regular/2560px-Starr_080607-7271_Brassica_campestris_var._chinensis.jpg'
),
(
'Asian Greens',
'Brassica rapa (Asian Greens Group)',
1.5,
'Annual',
7,
'Average',
'Part Shade',
false,
true,
'https://perenual.com/storage/species_image/1329_brassica_rapa_asian_greens_group/regular/Brassica_rapa_subsp_narinosa.jpg'
),
(
'Ornamental Cabbage',
'Brassica oleracea (Ornamental Cabbage and Kale Group)',
1.5,
'Annual',
7,
'Average',
'Part Shade',
false,
true,
'https://perenual.com/storage/species_image/1328_brassica_oleracea_ornamental_cabbage_and_kale_group/regular/318568954_0b66be78c0_b.jpg'
),
(
'Brussels Sprouts',
'Brassica oleracea (Gemmifera Group)',
1.5,
'Annual',
7,
'Average',
'Full Sun',
false,
true,
'https://perenual.com/storage/species_image/1325_brassica_oleracea_gemmifera_group/regular/brussels-sprouts-vegetables-brussels-carbon-sprouts-cabbage.jpg'
),
(
'Brugmansia',
'Brugmansia Pink Perfume',
6,
'Perennial',
9,
'Average',
'Full Sun',
true,
false,
'https://perenual.com/storage/species_image/1345_brugmansia_pink_perfume/regular/angel-trumpet-pink-toxic-flowers.jpg'
),
(
'Siberian bugloss',
'Brunnera macrophylla',
1.5,
'Perennial',
6,
'Average',
'Part Shade',
true,
false,
'https://perenual.com/storage/species_image/1347_brunnera_macrophylla/regular/28625503745_9a15156f64_b.jpg'
),
(
'Buffalo Grass',
'Buchloe dactyloides',
0.75,
'Perennial',
6,
'Minimum',
'Full Sun',
true,
false,
'https://perenual.com/storage/species_image/1359_buchloe_dactyloides/regular/8008288268_d2c6bcfdc0_b.jpg'
),
(
'Butterfly Bush',
'Buddleja Asian Moon',
7,
'Perennial',
7,
'Average',
'Full Sun',
true,
false,
'https://perenual.com/storage/species_image/1363_buddleja_asian_moon/regular/butterfly-bush-buddleia-buddleja-lilac.jpg'
),
(
'Mountain Sagewood',
'Buddleja loricata',
5,
'Perennial',
9,
'Average',
'Full Sun',
true,
false,
'https://perenual.com/storage/species_image/1389_buddleja_loricata/regular/Budd._loricata_flowers.jpg'
),
(
'Orange Bulbine',
'Bulbine frutescens',
1.5,
'Perennial',
10,
'Minimum',
'Full Sun',
true,
false,
'https://perenual.com/storage/species_image/1399_bulbine_frutescens/regular/39135511090_970d4428c8_b.jpg'
),
(
'South American Jelly Palm',
'Butia capitata',
35,
'Perennial',
10,
'Average',
'Full Sun',
true,
true,
'https://perenual.com/storage/species_image/1402_butia_capitata/regular/5582656068_8138ef55c1_b.jpg'
),
(
'Boxwood',
'Buxus Green Gem',
4,
'Perennial',
7,
'Average',
'Part Shade',
true,
false,
'https://perenual.com/storage/species_image/1405_buxus_green_gem/regular/50050401928_d0612ba253_b.jpg'
),
(
'Japanese Boxwood',
'Buxus microphylla var. japonica Morris Midget',
4,
'Perennial',
8,
'Average',
'Part Shade',
true,
false,
'https://perenual.com/storage/species_image/1419_buxus_microphylla_var_japonica_morris_midget/regular/24808513161_a90519f40d_b.jpg'
),
(
'Rattlesnake Plant',
'Calathea lancifolia',
1.5,
'Perennial',
12,
'Average',
'Part Shade',
true,
false,
'https://perenual.com/storage/species_image/1469_calathea_lancifolia/regular/3676781257_2e8730f471_b.jpg'
),
(
'Slipper Flower',
'slipper flower',
1,
'Perennial',
11,
'Average',
'Full Shade',
true,
false,
'https://perenual.com/storage/species_image/1472_calceolaria_herbeohybrida_group/regular/2428017395_db5e093bd6_b.jpg'
),
(
'Beautyberry',
'Callicarpa dichotoma',
4,
'Perennial',
7,
'Average',
'Full Sun',
true,
false,
'https://perenual.com/storage/species_image/1486_callicarpa_dichotoma_issai/regular/21657445250_d3c3fa3bb9_b.jpg'
),
(
'Wild Hyacinth',
'Camassia scilloides',
3,
'Perennial',
6,
'Average',
'Full Shade',
true,
false,
'https://perenual.com/storage/species_image/1525_camassia_scilloides/regular/52018796365_365b605111_b.jpg'
),
(
'Adriatic bellflower',
'Campanula garganica Dickson''s Gold',
0.5,
'Perennial',
6,
'Average',
'Part Shade',
true,
false,
'https://perenual.com/storage/species_image/1545_campanula_garganica_dicksons_gold/regular/51765369977_d73847f8f2_b.jpg'
),
(
'Carolina Allspice',
'Calycanthus raulstonii Hartlage Wine',
10,
'Perennial',
7,
'Average',
'Part Shade',
true,
false,
'https://perenual.com/storage/species_image/1516_calycanthus_raulstonii_hartlage_wine/regular/2560px-Calycanthus_raulstonii_27Hartlage_Wine272C_Morris_Arboretum_01.jpg'
),
(
'Crimson Bottlebrush',
'Callistemon citrinus',
5,
'Perennial',
10,
'Average',
'Full Sun',
true,
false,
'https://perenual.com/storage/species_image/1499_callistemon_citrinus/regular/49024199786_85bea4772f_b.jpg'
),
(
'Sallow Sedge',
'Carex lurida',
3,
'Perennial',
6,
'Average',
'Part Shade',
true,
false,
'https://perenual.com/storage/species_image/1645_carex_lurida/regular/51178147282_2dba5552a9_b.jpg'
),
(
'Cayenne Pepper',
'Capsicum annuum',
4,
'Perennial',
10,
'Average',
'Full Sun',
true,
true,
'https://perenual.com/storage/species_image/1595_capsicum_annuum/regular/51677548162_b86511d0e5_b.jpg'
);

-- TEST USER 1
INSERT INTO userInfo (first_name, last_name, username, email, password)
VALUES ('John', 'Doe', 'jdoe', 'johndoe@example.com','$2a$12$bzVplFpQhE5Dectai0eRQuqpv2Z6RgRXgMdFXNd5ffJm8jfJmeAfm');

INSERT INTO location (user_id, minHardiness, maxHardiness, watering, sunlight)
VALUES ((SELECT user_id FROM userInfo 
WHERE username = 'jdoe'), 5, 8, 'Average', 'Full Sun');

INSERT INTO user_to_plants (user_id,plant_id) VALUES 
((SELECT user_id FROM userInfo 
WHERE username = 'jdoe'),1),
((SELECT user_id FROM userInfo 
WHERE username = 'jdoe'),2),
((SELECT user_id FROM userInfo 
WHERE username = 'jdoe'),3);

-- TEST USER 2
INSERT INTO userInfo (first_name, last_name, username, email, password)
VALUES ('Bob', 'Ross', 'bross', 'happytrees@example.com','$2a$12$bzVplFpQhE5Dectai0eRQuqpv2Z6RgRXgMdFXNd5ffJm8jfJmeAfm');

INSERT INTO user_to_plants (user_id,plant_id) VALUES 
((SELECT user_id FROM userInfo 
WHERE username = 'bross'),1),
((SELECT user_id FROM userInfo 
WHERE username = 'bross'),3),
((SELECT user_id FROM userInfo 
WHERE username = 'bross'),5),
((SELECT user_id FROM userInfo 
WHERE username = 'bross'),7),
((SELECT user_id FROM userInfo 
WHERE username = 'bross'),9),
((SELECT user_id FROM userInfo 
WHERE username = 'bross'),11),
((SELECT user_id FROM userInfo 
WHERE username = 'bross'),13),
((SELECT user_id FROM userInfo 
WHERE username = 'bross'),15),
((SELECT user_id FROM userInfo 
WHERE username = 'bross'),17);
